# [dbo].[CTDONDH]

In [0]:
USE [HOMEWORK_SQL_LESSON02]
GO

In [0]:
/****** Object:  Table [dbo].[CTDONDH]    Script Date: 12/8/2023 11:24:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTDONDH](
	[SODH] [nvarchar](100) NOT NULL,
	[MAVTU] [nvarchar](50) NULL,
	[SLDAT] [nvarchar](50) NULL,
 CONSTRAINT [PK_CTDONDH] PRIMARY KEY CLUSTERED 
(
	[SODH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[CTPNHAP]

In [0]:
/****** Object:  Table [dbo].[CTPNHAP]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTPNHAP](
	[SONPN] [nvarchar](50) NULL,
	[MAVTU] [nvarchar](50) NULL,
	[SLNHAP] [nvarchar](50) NULL,
	[DGNHAP] [nvarchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[CTPXUAT]

In [0]:
/****** Object:  Table [dbo].[CTPXUAT]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTPXUAT](
	[SOPX] [nvarchar](50) NULL,
	[MAVTU] [nvarchar](50) NULL,
	[SLXUAT] [nvarchar](50) NULL,
	[DGXUAT] [nvarchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[DONDHH]

In [0]:
/****** Object:  Table [dbo].[DONDHH]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONDHH](
	[SODH] [nvarchar](50) NULL,
	[NGAYDH] [datetime] NULL,
	[MANHACC] [nvarchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[NHACC]

In [0]:
/****** Object:  Table [dbo].[NHACC]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHACC](
	[MANHACC] [nvarchar](50) NOT NULL,
	[TENHACC] [nvarchar](150) NULL,
	[DIACHI] [nvarchar](50) NULL,
	[DIENTHOAI] [nvarchar](50) NULL,
 CONSTRAINT [PK_NHACC] PRIMARY KEY CLUSTERED 
(
	[MANHACC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[PNHAP]

In [0]:
/****** Object:  Table [dbo].[PNHAP]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PNHAP](
	[SOPN] [nvarchar](50) NULL,
	[NGAYNHAP] [datetime] NULL,
	[SODH] [nvarchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[PXUAT]

In [0]:
/****** Object:  Table [dbo].[PXUAT]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PXUAT](
	[SOPX] [nvarchar](50) NOT NULL,
	[NGAYXUAT] [datetime] NULL,
	[TENKH] [nvarchar](100) NULL,
 CONSTRAINT [PK_PXUAT] PRIMARY KEY CLUSTERED 
(
	[SOPX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TONKHO]

In [0]:
/****** Object:  Table [dbo].[TONKHO]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TONKHO](
	[NAMTHANG] [datetime] NOT NULL,
	[MAVTU] [nvarchar](50) NULL,
	[SLDAU] [nvarchar](50) NULL,
	[TONGSLN] [nvarchar](50) NULL,
	[TONGSLX] [nvarchar](50) NULL,
	[SLCUOI] [nvarchar](50) NULL,
 CONSTRAINT [PK_TONKHO] PRIMARY KEY CLUSTERED 
(
	[NAMTHANG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[VATTU]

In [0]:
/****** Object:  Table [dbo].[VATTU]    Script Date: 12/8/2023 11:24:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VATTU](
	[MAVTU] [nvarchar](50) NULL,
	[TENVTU] [nvarchar](150) NULL,
	[DVITINH] [nvarchar](50) NULL,
	[PHANTRAM] [nvarchar](50) NULL
) ON [PRIMARY]
GO